export type Gender = 'MALE' | 'FEMALE'
export type FamilyRole = 'FATHER' | 'MOTHER' | 'SISTER' | 'BROTHER'
export type DayOfWeek = 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY' | 'SUNDAY'
export type NotificationType = 'WALK' | 'CHAT' | 'FRIEND'
export type Provider = 'GOOGLE' | 'NAVER' | 'KAKAO'
export type ChatType = 'TALK' | 'SYSTEM'
